---
title: "MALDI_new"
author: "Anji Deng"
date: '2023-12-08'
output:
  html_document: default
  pdf_document: default
---

```{r echo=FALSE, warning=FALSE,message=FALSE}
rm(list = ls())
```

```{r echo=FALSE, warning=FALSE,message=FALSE}
library(ggplot2)
library(dplyr)
library(htmltools)
library(plotly)
```

```{r echo=FALSE, warning=FALSE,message=FALSE}
setwd('/Users/anjideng1/Desktop/MALDI/')
```

### par3 (0.5, 0.9, 0.9)

```{r echo=FALSE}
### classification accuracy
accuracy_df <- data.frame('Not_aligned' = c(0.8581900034630036, 0.9952663431002456, 0.9511468079821148, 0.9896533044420368,
                                            0.8914429779030105, 0.9900364736233431, 0.9758132657372202, 0.9538058466629895),
                          'Aligned' = c(0.8543806995267228, 0.9902031278087363, 0.9340067897656703, 0.9733477789815818,
                                        0.9093133620050423, 0.9230940307801797, 0.9941909590198563, 0.9566556352270638),
                          'New_aligned' = c(0.8550733002424102, 0.9934088321648991, 0.9468825039330959, 0.9852654387865656,
                                           0.8852142963072817, 0.992660795302909, 0.9954583861427968, 0.9509100937672367))

accuracy <- data.frame('accuracy' = c(accuracy_df$Not_aligned, accuracy_df$New_aligned),
                       'index' = c(rep("Before Alignment", 8), rep("After Alignment", 8)))
colnames(accuracy_df) <- c("Before Alignment", "After Alignment")
```


```{r}
boxplot <- ggplot(accuracy) +
  geom_boxplot(aes(x = index, y = accuracy), fill = "light blue", width = 0.4) +
  labs(x = "", y = "Classification Accuracy") +
  annotate("label", x = 1.5, y = 1, label = "p-value = 0.16", size = 10) +
  theme_bw()

plotly::ggplotly(boxplot)
```


```{r}
ggsave(file = "boxplot_par3_Ds2.png", width = 10, height = 8, dpi = 300)
```


```{r echo=FALSE}
# 6. Compare the aligned spectrum -------------------------------------------------

## Read the original file
table <- NULL
for (id in c('normal', 'cancer', 'aligned')){
  tablei <- read.csv(paste0("output/new_mean/new_ds2_par3_", id, ".csv"), header = T)
  colnames(tablei) <- NULL
  table <- rbind(table, data.frame(tablei, type = id))
}
```

```{r echo=FALSE}
# old_align <- read.csv("output/ds2_par3_aligned.csv")
# old_align$types <- c("old_aligned")
# old_align <- data.frame('types' = old_align$types, 'intensity' = old_align$intensity, 'mzvalues' = old_align$mzvalues)
```


```{r echo=FALSE}
table$types = factor(table$type, levels = c('normal', 'cancer', 'aligned'), 
                     labels = c("normal", "cancer", "aligned"))

table <- table %>%
  mutate(intensity = X2) %>%
  mutate(mzvalues = X1)

# table <- rbind(table[, 4:6], old_align)
```


```{r echo=FALSE}
color_palatte <- c("#CAE7B9", "#F3DE8A",  "#EB9486", "#7E7F9A", "#565F41", "#D1D1D1","#6D1A9C","#15821E","#3A84E6","#997273")
strip_color <- "#0A1D37"
```

```{r echo=FALSE}
shift_data = read.csv('output/new_shift/mzshifting_Ds2_par3.csv')
shift_data
```
```{r}
MZshiftingdataplot <- data.frame(mzvalues = c(shift_data$mzvalue_start, shift_data$mzvalue_end), shift = rep(shift_data$shift_fromorigin,2)) %>%
  arrange(mzvalues)

MZshiftingdataplot$shift_mz <- MZshiftingdataplot$shift * 0.5
```

```{r echo=FALSE}
shiftplot <- ggplot(MZshiftingdataplot) + 
  geom_line(aes(y=shift_mz, x=mzvalues), size = 1) + 
  geom_point(aes(y=shift_mz, x=mzvalues), size = 0.8) + 
  scale_color_manual(values=color_palatte) + 
  labs(x = "m/z values", y = "shift in m/z") + 
  scale_x_continuous(breaks = seq(100, 2000, by = 100)) +
  ## coord_cartesian(ylim = c(0.2, 0.8)) +
  ## geom_vline(xintercept=c(21, 25, 50, 188, 250, 440, 600, 880), linetype=2, color = "#B3B6B7", size = 0.3)+
  theme_bw()  +
  theme(text = element_text(size=16, family="URWHelvetica"),  axis.text = element_text(size = 16, family="URWHelvetica"), panel.spacing = unit(1, "lines")) +
  theme(strip.background = element_rect(fill=strip_color,color=strip_color))+ # #535b44
  theme(strip.text = element_text(colour = 'white')) +
  theme(panel.border = element_rect(colour = strip_color), legend.position = "none") +
  theme(axis.text = element_text(size = 20), axis.title=element_text(size = 25))

plotly::ggplotly(shiftplot)
```


```{r echo=FALSE}
ggsave(file = "shift_plot_par3.png", width = 18, height = 4, dpi = 300)
```




```{r echo=FALSE}
lineplot <- ggplot(table) + 
  geom_line(aes(y=log(intensity), x=mzvalues, color = types), size = 0.3) + 
  # geom_point(aes(y=intensity, x=mzvalues, color = weeks), size = 0.6, data = table2) + 
  # geom_segment(aes(x = start, y = ylevel, xend = end, yend = ylevel), size = 0.6,  data = table3) +
  scale_color_manual(values=color_palatte) + 
  labs(x = "m/z values", y = "intensity") + 
  facet_grid(types~., scales = "free_y") + 
  # coord_cartesian(ylim = c(0.2, 0.8)) +
  # geom_vline(xintercept=c(21, 25, 50, 188, 250, 440, 600, 880), linetype=2, color = "#B3B6B7", size = 0.3)+
  theme_bw()  +
  # scale_y_log10() +
  theme(text = element_text(size=16, family="URWHelvetica"),  axis.text = element_text(size = 16, family="URWHelvetica"), panel.spacing = unit(1, "lines") ) +
  theme(strip.background = element_rect(fill=strip_color,color=strip_color))+ # #535b44
  theme(strip.text = element_text(colour = 'white')) +
  theme(panel.border = element_rect(colour = strip_color), legend.position = "none")

plotly::ggplotly(lineplot) # 205* (extra bump at the left disappear), 516-526*, 666, 922, 1729*, 1832
```

```{r}
breaks <- c(-Inf, 195, 215, 510, 530, 1720, 1740, Inf)
table$example_ind <- cut(table$mzvalues, breaks = breaks, 
                         labels = c("0", "Example 1", "0", "Example 2", "0", "Example 3", "0"))

table <- table %>%
  mutate(vline1 = case_when(example_ind == "0" ~ 0,
                           example_ind == "Example 1" ~ 199, 
                           example_ind == "Example 2" ~ 514.5,
                           example_ind == "Example 3" ~ 1730))

table <- table %>%
  mutate(vline2 = case_when(example_ind == "0" ~ 0,
                           example_ind == "Example 1" ~ 200, # 200.5
                           example_ind == "Example 2" ~ 523, # 523.5
                           example_ind == "Example 3" ~ NA))

table <- table %>%
  mutate(vline3 = case_when(example_ind == "0" ~ 0,
                           example_ind == "Example 1" ~ 204, # 200.5
                           example_ind == "Example 2" ~ 524,
                           example_ind == "Example 3" ~ NA))
```

```{r warning=FALSE}
lineplot <- ggplot(subset(table, example_ind %in% c("Example 1", "Example 2", "Example 3"))) + 
  geom_line(aes(y=log(intensity), x=mzvalues, color = types), size = 1) + 
  # geom_point(aes(y=intensity, x=mzvalues, color = weeks), size = 0.6, data = table2) + 
  # geom_segment(aes(x = start, y = ylevel, xend = end, yend = ylevel), size = 0.6,  data = table3) +
  scale_color_manual(values=color_palatte) + 
  labs(x = "m/z values", y = "log intensity") + 
  # facet_grid(types~., scales = "free_y") + 
  #facet_grid(rows = vars(types)) +
  facet_grid(vars(types), vars(example_ind), scales = "free") +
  geom_vline(aes(xintercept = vline1), colour = "darkgrey", linetype = 2, size = 0.8) + 
  geom_vline(aes(xintercept = vline2), colour = "darkgrey", linetype = 2, size = 0.8) + 
  geom_vline(aes(xintercept = vline3), colour = "darkgrey", linetype = 2, size = 0.8) +
  # coord_cartesian(ylim = c(0.2, 0.8)) +
  # geom_vline(xintercept=c(21, 25, 50, 188, 250, 440, 600, 880), linetype=2, color = "#B3B6B7", size = 0.3)+
  theme_bw()  +
  # scale_y_log10() + # equal space for log 10
  theme(text = element_text(size=16, family="URWHelvetica"),  axis.text = element_text(size = 16, family="URWHelvetica"), panel.spacing = unit(1, "lines") ) +
  theme(strip.background = element_rect(fill=strip_color,color=strip_color))+ # #535b44
  theme(strip.text = element_text(colour = 'white')) +
  theme(panel.border = element_rect(colour = strip_color), legend.position = "none") +
  theme(axis.text = element_text(size = 20), axis.title=element_text(size = 28),
        strip.text = element_text(size = 25)) +
  theme(panel.spacing.x = unit(10, "mm"))
  


plotly::ggplotly(lineplot) # 205* (extra bump at the left disappear), 516-526*, 666, 922, 1729*, 1832
```

```{r}
ggsave(file = "spectrum_plot_par3_Ds2.png", width = 12, height = 8, dpi = 300)
```


